# Gunakan image Node.js yang ringan
FROM node:18-alpine

# Tentukan folder kerja
WORKDIR /app

# Salin dan install dependency
COPY package*.json ./
RUN npm install --production

# Salin semua file source code
COPY . .

# Pastikan server bisa diakses dari luar container
EXPOSE 5000

# Jalankan server
CMD ["node", "server.js"]
